2019-03-28 14:27:10,791 ERROR 10156 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at ConnectionManager._connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/lifecycle.js:248:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 10156
hostname: yangfandeMacBook-Pro.local

2019-03-28 14:29:28,843 ERROR 10196 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at ConnectionManager._connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/lifecycle.js:248:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 10196
hostname: yangfandeMacBook-Pro.local

2019-03-28 14:29:32,288 ERROR 10199 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at ConnectionManager._connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/lifecycle.js:248:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 10199
hostname: yangfandeMacBook-Pro.local

2019-03-28 14:34:26,207 ERROR 10499 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at ConnectionManager._connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/lifecycle.js:248:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 10499
hostname: yangfandeMacBook-Pro.local

2019-03-28 14:35:00,818 ERROR 10504 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at ConnectionManager._connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/lifecycle.js:248:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 10504
hostname: yangfandeMacBook-Pro.local

2019-03-28 14:35:15,066 ERROR 10513 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at ConnectionManager._connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/lifecycle.js:248:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 10513
hostname: yangfandeMacBook-Pro.local

2019-03-28 14:36:07,693 ERROR 10529 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at Utils.Promise.tap.then.catch.err (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
From previous event:
    at ConnectionManager.connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:136:13)
    at sequelize.runHooks.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:50)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at ConnectionManager._connect (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:320:8)
    at ConnectionManager.getConnection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:46)
    at Promise.try (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:64)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at Sequelize.authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:783:17)
    at authenticate (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:129:22)
    at Promise.all.databases.map.database (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:49)
    at Array.map (<anonymous>)
    at app.beforeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-sequelize/lib/loader.js:40:33)
    at Object.callFn (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/utils/index.js:44:42)
    at process.nextTick (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/lifecycle.js:248:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 10529
hostname: yangfandeMacBook-Pro.local

2019-03-28 15:26:51,826 ERROR 11797 nodejs.SequelizeDatabaseError: Unknown column 'users.phone' in 'where clause'
    at Query.formatError (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:79:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Query.run (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:555:8)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.select (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/query-interface.js:1104:27)
    at Promise.try.then.then.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:1598:34)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Function.findAll (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:1595:8)
    at BaseService.isHaveUser (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/service/base.js:8:39)
    at LoginController.index (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/controller/login.js:9:45)
    at Object.callFn (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/node_modules/koa-compose/index.js:45:18)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/node_modules/koa-compose/index.js:44:32)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at xframe (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'users.phone' in 'where clause'","sql":"SELECT `user_id`, `name`, `age`, `created_at`, `updated_at` FROM `users` AS `users` WHERE `users`.`phone` = '111' AND `users`.`password` = '';"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'users.phone' in 'where clause'","sql":"SELECT `user_id`, `name`, `age`, `created_at`, `updated_at` FROM `users` AS `users` WHERE `users`.`phone` = '111' AND `users`.`password` = '';"}
sql: "SELECT `user_id`, `name`, `age`, `created_at`, `updated_at` FROM `users` AS `users` WHERE `users`.`phone` = '111' AND `users`.`password` = '';"
pid: 11797
hostname: yangfandeMacBook-Pro.local

2019-03-28 15:27:17,359 ERROR 11805 nodejs.SequelizeDatabaseError: Unknown column 'users.phone' in 'where clause'
    at Query.formatError (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:79:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Query.run (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:555:8)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.select (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/query-interface.js:1104:27)
    at Promise.try.then.then.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:1598:34)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Function.findAll (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:1595:8)
    at BaseService.isHaveUser (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/service/base.js:8:45)
    at LoginController.index (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/controller/login.js:9:45)
    at Object.callFn (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/node_modules/koa-compose/index.js:45:18)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/node_modules/koa-compose/index.js:44:32)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/@eggjs/router/lib/router.js:195:33)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at i18n (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at dta (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at xframe (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
    at xssProtection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/koa-compose/index.js:42:32)
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'users.phone' in 'where clause'","sql":"SELECT `user_id`, `name`, `age`, `created_at`, `updated_at` FROM `users` AS `users` WHERE `users`.`phone` = '111' AND `users`.`password` = '';"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'users.phone' in 'where clause'","sql":"SELECT `user_id`, `name`, `age`, `created_at`, `updated_at` FROM `users` AS `users` WHERE `users`.`phone` = '111' AND `users`.`password` = '';"}
sql: "SELECT `user_id`, `name`, `age`, `created_at`, `updated_at` FROM `users` AS `users` WHERE `users`.`phone` = '111' AND `users`.`password` = '';"
pid: 11805
hostname: yangfandeMacBook-Pro.local

2019-03-28 18:03:28,892 ERROR 13898 [-/172.18.11.29/-/34ms POST /register] nodejs.SequelizeDatabaseError: Column 'user_id' cannot be null
    at Query.formatError (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:79:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Query.run (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:555:8)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.insert (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/query-interface.js:901:27)
    at Promise.try.then.then.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3685:53)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at model.save (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3661:8)
    at Function.create (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:2023:8)
    at BaseService.addUser (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/service/base.js:16:45)
    at RegisterContorller.index (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/controller/register.js:20:54)
    at <anonymous>
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_NULL_ERROR","errno":1048,"sqlState":"23000","sqlMessage":"Column 'user_id' cannot be null","sql":"INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:03:28','2019-03-28 18:03:28');"}
original: {"code":"ER_BAD_NULL_ERROR","errno":1048,"sqlState":"23000","sqlMessage":"Column 'user_id' cannot be null","sql":"INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:03:28','2019-03-28 18:03:28');"}
sql: "INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:03:28','2019-03-28 18:03:28');"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 13898
hostname: yangfandeMacBook-Pro.local

2019-03-28 18:05:32,515 ERROR 13898 [-/172.18.11.29/-/28ms POST /register] nodejs.SequelizeDatabaseError: Column 'user_id' cannot be null
    at Query.formatError (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:79:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Query.run (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:555:8)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.insert (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/query-interface.js:901:27)
    at Promise.try.then.then.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3685:53)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at model.save (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3661:8)
    at Function.create (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:2023:8)
    at BaseService.addUser (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/service/base.js:16:45)
    at RegisterContorller.index (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/controller/register.js:20:54)
    at <anonymous>
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_NULL_ERROR","errno":1048,"sqlState":"23000","sqlMessage":"Column 'user_id' cannot be null","sql":"INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:05:32','2019-03-28 18:05:32');"}
original: {"code":"ER_BAD_NULL_ERROR","errno":1048,"sqlState":"23000","sqlMessage":"Column 'user_id' cannot be null","sql":"INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:05:32','2019-03-28 18:05:32');"}
sql: "INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:05:32','2019-03-28 18:05:32');"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 13898
hostname: yangfandeMacBook-Pro.local

2019-03-28 18:05:43,439 ERROR 13898 [-/172.18.11.29/-/17ms POST /register] nodejs.SequelizeDatabaseError: Column 'user_id' cannot be null
    at Query.formatError (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:79:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Query.run (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:555:8)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.insert (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/query-interface.js:901:27)
    at Promise.try.then.then.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3685:53)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at model.save (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3661:8)
    at Function.create (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:2023:8)
    at BaseService.addUser (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/service/base.js:16:45)
    at RegisterContorller.index (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/controller/register.js:20:54)
    at <anonymous>
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_NULL_ERROR","errno":1048,"sqlState":"23000","sqlMessage":"Column 'user_id' cannot be null","sql":"INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:05:43','2019-03-28 18:05:43');"}
original: {"code":"ER_BAD_NULL_ERROR","errno":1048,"sqlState":"23000","sqlMessage":"Column 'user_id' cannot be null","sql":"INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:05:43','2019-03-28 18:05:43');"}
sql: "INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:05:43','2019-03-28 18:05:43');"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 13898
hostname: yangfandeMacBook-Pro.local

2019-03-28 18:06:36,693 ERROR 13919 [-/172.18.11.29/-/64ms POST /register] nodejs.SequelizeDatabaseError: Column 'user_id' cannot be null
    at Query.formatError (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:79:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Query.run (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:555:8)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.insert (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/query-interface.js:901:27)
    at Promise.try.then.then.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3685:53)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at model.save (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3661:8)
    at Function.create (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:2023:8)
    at BaseService.addUser (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/service/base.js:16:45)
    at RegisterContorller.index (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/controller/register.js:20:54)
    at <anonymous>
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_NULL_ERROR","errno":1048,"sqlState":"23000","sqlMessage":"Column 'user_id' cannot be null","sql":"INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:06:36','2019-03-28 18:06:36');"}
original: {"code":"ER_BAD_NULL_ERROR","errno":1048,"sqlState":"23000","sqlMessage":"Column 'user_id' cannot be null","sql":"INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:06:36','2019-03-28 18:06:36');"}
sql: "INSERT INTO `users` (`user_id`,`phone`,`created_at`,`updated_at`) VALUES (NULL,'[object Object]','2019-03-28 18:06:36','2019-03-28 18:06:36');"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 13919
hostname: yangfandeMacBook-Pro.local

2019-03-28 18:08:12,712 ERROR 13956 [-/172.18.11.29/-/68ms POST /register] nodejs.SequelizeDatabaseError: Column 'user_id' cannot be null
    at Query.formatError (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/mysql2/lib/connection.js:79:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Query.run (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:555:8)
    at /Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.insert (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/query-interface.js:901:27)
    at Promise.try.then.then.then (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3685:53)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at model.save (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3661:8)
    at Function.create (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:2023:8)
    at BaseService.addUser (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/service/base.js:16:45)
    at RegisterContorller.index (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/controller/register.js:20:54)
    at <anonymous>
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_NULL_ERROR","errno":1048,"sqlState":"23000","sqlMessage":"Column 'user_id' cannot be null","sql":"INSERT INTO `users` (`user_id`,`phone`,`password`,`age`,`created_at`,`updated_at`) VALUES (NULL,'18797814591','2211',18,'2019-03-28 18:08:12','2019-03-28 18:08:12');"}
original: {"code":"ER_BAD_NULL_ERROR","errno":1048,"sqlState":"23000","sqlMessage":"Column 'user_id' cannot be null","sql":"INSERT INTO `users` (`user_id`,`phone`,`password`,`age`,`created_at`,`updated_at`) VALUES (NULL,'18797814591','2211',18,'2019-03-28 18:08:12','2019-03-28 18:08:12');"}
sql: "INSERT INTO `users` (`user_id`,`phone`,`password`,`age`,`created_at`,`updated_at`) VALUES (NULL,'18797814591','2211',18,'2019-03-28 18:08:12','2019-03-28 18:08:12');"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 13956
hostname: yangfandeMacBook-Pro.local

2019-03-28 22:02:48,722 ERROR 11910 nodejs.ClusterClientNoResponseError: client no response in 357370ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 11910
hostname: yangfandeMacBook-Pro.local

2019-03-29 08:54:52,297 ERROR 11910 nodejs.ClusterClientNoResponseError: client no response in 39043512ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 11910
hostname: yangfandeMacBook-Pro.local

2019-03-29 09:12:32,222 ERROR 11910 nodejs.ClusterClientNoResponseError: client no response in 1059620ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 11910
hostname: yangfandeMacBook-Pro.local

2019-03-29 10:05:50,181 ERROR 16328 [-/172.18.11.29/-/43ms POST /user/modify] nodejs.AssertionError [ERR_ASSERTION]: Missing where attribute in the options parameter
    at Function._optionsMustContainWhere (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3044:5)
    at Function.update (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:2666:10)
    at BaseService.modify (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/service/base/user.js:24:45)
    at ModifyConroller.index (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/controller/user/modify.js:33:58)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 16328
hostname: yangfandeMacBook-Pro.local

2019-03-29 10:11:18,949 ERROR 16374 [-/172.18.11.29/-/10ms POST /user/modify] nodejs.AssertionError [ERR_ASSERTION]: Missing where attribute in the options parameter
    at Function._optionsMustContainWhere (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3044:5)
    at Function.update (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:2666:10)
    at BaseService.modify (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/service/base/user.js:24:45)
    at ModifyConroller.index (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/controller/user/modify.js:36:58)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 16374
hostname: yangfandeMacBook-Pro.local

2019-03-29 10:11:30,100 ERROR 16380 [-/172.18.11.29/-/29ms POST /user/modify] nodejs.AssertionError [ERR_ASSERTION]: Missing where attribute in the options parameter
    at Function._optionsMustContainWhere (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:3044:5)
    at Function.update (/Users/yangfan/Desktop/yf/my-mall/mall-service/node_modules/sequelize/lib/model.js:2666:10)
    at BaseService.modify (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/service/base/user.js:24:45)
    at ModifyConroller.index (/Users/yangfan/Desktop/yf/my-mall/mall-service/app/controller/user/modify.js:34:58)
    at <anonymous>
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 16380
hostname: yangfandeMacBook-Pro.local

